<?php
/**
 * The URL to the Github Markdown API. See https://docs.github.com/en/rest/markdown/markdown?apiVersion=2022-11-28.
 * @var string
 */
const MARKDOWN_URL = 'https://api.github.com/markdown';

/**
 * Calls GitHub Markdown API to retrieve the HTML representation of a given markdown string. The API ensures the HTML doesn't contain XSS.
 * @param string $data The input markdown string.
 * @return bool|string HTML result or `false` on cURL failure.
 */
function markdownGithub(string $data)
{
    $payload = json_encode([
        'text' => $data,
        'mode' => 'gfm',
    ]);

    $curlHandle = curl_init(MARKDOWN_URL);
    curl_setopt_array($curlHandle, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_HTTPHEADER => [
            'Accept: application/vnd.github+json',
            'Accept-Language: en,en-US;q=0.7,cs;q=0.3',
            'Content-Type: application/json',
            'Cache-Control: no-cache',
            'Connection: keep-alive',
            'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
            'X-GitHub-Api-Version: 2022-11-28',
        ],
        CURLOPT_POSTFIELDS => $payload,
    ]);

    $response = curl_exec($curlHandle);
    curl_close($curlHandle);

    return $response;
}

/**
 * Runs several correction regexes on the HTML code generated by GitHub to be valid.
 * @param string $htmlData The HTML code generated by GitHub markdown API.
 * @return string The result HTML code.
 */
function fixGithubHtml($htmlData) {
    //  Remove <a></a> tags surrounding an <img> tag.
    $pattern = '#<a\b[^>]*>\s*(<img\b[^>]*>)\s*</a>#i';
    $replacement = '$1';
    $htmlData = preg_replace($pattern, $replacement, $htmlData);

    // Remove src from <img> tags with data-canonical-src attribute
    $pattern = '#<img\b(?=[^>]*\bdata-canonical-src\b)[^>]*\K\s+\bsrc\s*=\s*(["\']).*?\1#i';
    $htmlData = preg_replace($pattern, '', $htmlData);

    // Replace data-canonical-src with src attributes
    $pattern = '#\bdata-canonical-src\b\s*=\s*(["\'])(.*?)\1#i';
    $replacement = 'src=$1$2$1';
    $htmlData = preg_replace($pattern, $replacement, $htmlData);

    // Remove all style tags from the code
    $pattern = '#<\w+\b[^>]*\K\s+\bstyle\s*=\s*(["\']).*?\1#i';
    $htmlData = preg_replace($pattern, '', $htmlData);

    // Replace h{n} tags with h{+1} tag, until 6
    $htmlData = preg_replace_callback(
        '#</?h([1-6])\b#i',
        function ($m) {
            $level = (int)$m[1];
            $new   = min($level + 1, 6);
            return str_ireplace("h{$level}", "h{$new}", $m[0]);
        },
        $htmlData
    );

    // Remove role="table" as it is invalid HTML
    $pattern = '#<table\b[^>]*\K\s+\brole\s*=\s*(["\']).*?\1#i';
    $htmlData = preg_replace($pattern, '', $htmlData);
    
    return $htmlData;
}