<?php
// Prefill the form in case it's sent back
$prefillTitle = isset($_POST['title']) ? htmlspecialchars($_POST['title']) : '';
$prefillDescription = isset($_POST['description']) ? htmlspecialchars($_POST['description']) : '';
$prefillCategory = isset($_POST['category']) ? htmlspecialchars($_POST['category']) : '';
$prefillMarkdown = isset($_POST['markdown-article']) ? htmlspecialchars($_POST['markdown-article']) : '';
// Get session csrf-token
$csrfToken = $_SESSION['csrf-token'];
session_write_close();
?>
<main>
    <h1>Create a new Project</h1>
    <div>
        Fields marked with <span class="color-required">*</span> are required!
    </div>
    <form method="post" enctype="multipart/form-data">
        <h2>Introduction</h2>
        <div class="introduction-part">
            <div class="introduction-details">
                <div class="field">
                    <label for="input-title">Title of your project:</label>
                    <input id="input-title" name="title" type="text" value="<?= $prefillTitle ?>" required>
                </div>
                <div class="field">
                    <label for="input-description">Brief description:</label>
                    <textarea id="input-description" name="description" type="text" required><?= $prefillDescription ?></textarea>
                </div>
                <div class="field">
                    <label for="input-thumbnail">Thumbnail:</label>
                    <div>
                        <p class="thumbnail-size">The image must be JPEG, PNG or WEBP of 8MB at most!</p>
	                    <p class="thumbnail-ratio">The image needs to have 16:9 aspect ratio!</p>
                    </div>
                    <input id="input-thumbnail" name="thumbnail" type="file" accept=".jpeg,.jpg,.png,.webp" required></input>
                </div>
            </div>
            <div class="introduction-preview">
                <div>
                    Crazy
                </div>
            </div>
        </div>
        <h2>Project Details</h2>
        <div class="details-part">
            <div class="field slug-editor">
                <label for="input-slug">URL path on the website - leave empty to set automatically:</label>
                <div class="prefix-container">
                    <label for="input-slug">/projects/</label>
                    <input id="input-slug" name="slug" type="text" value="">
                </div>
            </div>
            <div class="field category-selection">
                <label for="input-category">Category:</label>
                <select id="input-category" name="category" value="<?= $prefillCategory ?>" required></select>
            </div>
        </div>
        <h2>Article Contents</h2>
        <div class="article-part">
            <div class="article-editor field">
                <label for="md-input">Your project's article, use <a href="https://github.github.com/gfm/"
                        title="GFM Spec" target="_blank">GitHub Flavored Markdown</a>:</label>
                <div class="switch-buttons">
                    <button id="btn-edit-article" disabled>Edit</button>
                    <button id="btn-preview-article">Preview</button>
                </div>
                <textarea id="md-input" name="markdown-article" required><?= $prefillMarkdown ?></textarea>
                <div id="md-preview" class="hidden"></div>
            </div>
            <div class="article-gallery">
                <div class="gallery-info">
                    You can upload images to accompany your article. Click them to get
                    their link to use them in markdown of your article.
                </div>
                <ul id="gallery-preview">
                    <!-- This content is generated by a script!  -->
                </ul>
            </div>
        </div>
        <h2>Downloads & Links</h2>
        <div class="downloads-part">
            <div class="field">
            <h3>Upload a file</h3>
            <div id="file-adder">
                <div>
                    <p>File #1 to download the project.</p>
                    <label for="input-link-url-0">URL:</label>
                    <input type="text" name="link-url[0]" id="input-link-url-0">
                    <label for="input-link-name-0">Display Name:</label>
                    <input type="text" name="link-name[0]" id="input-link-name-0">
                </div>
            </div>
            </div>
            <div class="field">
            <h3>Add a link</h3>
            <div id="link-adder">
                <div>
                    <p>Link #1 to download the project.</p>
                    <label for="input-link-url-0">URL:</label>
                    <input type="text" name="link-url[0]" id="input-link-url-0">
                    <label for="input-link-name-0">Display Name:</label>
                    <input type="text" name="link-name[0]" id="input-link-name-0">
                </div>
            </div>
            </div>
            <input type="submit" value="Create Project">
        </div>
        <input type="hidden" name="csrf-token" value="<?= $csrfToken ?>">
    </form>
</main>