<?php
$viewState = ViewData::getInstance();

$prefillEditing = $viewState->get('form-editing','0');
$prefillTitle = htmlspecialchars($viewState->get('form-title',''));
$prefillDescription = htmlspecialchars($viewState->get('form-description',''));
$prefillSlug = htmlspecialchars($viewState->get('form-slug',''));
$prefillCategory = htmlspecialchars($viewState->get('form-category',''));
$prefillMarkdown = htmlspecialchars($viewState->get('form-markdown-article',''));

$username = $viewState->get('verified-username','');


// Get session csrf-token
$csrfToken = $_SESSION['csrf-token'];
?>
<main>
    <h1>Create a new Project</h1>
    <div>
        Fields marked with <span class="color-required">*</span> are required!
    </div>
    <form method="post" enctype="multipart/form-data">
        <h2>Introduction</h2>
        <div class="introduction-part">
            <div class="introduction-details">
                <div class="field">
                    <label for="input-title">Title of your project:</label>
                    <input id="input-title" name="title" type="text" value="<?= $prefillTitle ?>" minlength="6" maxlength="128" required>
                </div>
                <div class="field">
                    <label for="input-description">Brief description:</label>
                    <textarea id="input-description" name="description" type="text" minlength="24" maxlength="256" required><?= $prefillDescription ?></textarea>
                </div>
                <div class="field">
                    <label for="input-thumbnail">Thumbnail:</label>
                    <div>
                        <p class="thumbnail-size">The image must be JPEG, PNG or WEBP of 8MB at most!</p>
	                    <p class="thumbnail-ratio">The image needs to have 16:9 aspect ratio!</p>
                    </div>
                    <input id="input-thumbnail" name="thumbnail" type="file" accept=".jpeg,.jpg,.png,.webp" required></input>
                </div>
            </div>
            <div class="introduction-preview">
                <div class="project-card">
                    <div class="user-part">

                    </div>
                    <div>

                    </div>
                </div>
            </div>
        </div>
        <h2>Project Details</h2>
        <div class="details-part">
            <div class="field slug-editor">
                <label for="input-slug">URL path on the website - leave empty to set automatically:</label>
                <div class="prefix-container">
                    <label for="input-slug">/projects/</label>
                    <input id="input-slug" name="slug" type="text" value="<?= $prefillSlug ?>">
                </div>
            </div>
            <div class="field category-selection">
                <label for="input-category">Category:</label>
                <select id="input-category" name="category" value="<?= $prefillCategory ?>" required></select>
            </div>
        </div>
        <h2>Article Contents</h2>
        <div class="article-part">
            <div class="article-editor field">
                <label for="md-input">Your project's article, use <a href="https://github.github.com/gfm/"
                        title="GFM Spec" target="_blank">GitHub Flavored Markdown</a>:</label>
                <div class="switch-buttons">
                    <button id="btn-edit-article" disabled>Edit</button>
                    <button id="btn-preview-article">Preview</button>
                </div>
                <textarea id="md-input" name="markdown-article" minlength="128" maxlength="4096" required><?= $prefillMarkdown ?></textarea>
                <div id="md-preview" class="hidden"></div>
            </div>
            <div class="article-gallery">
                <div class="gallery-info">
                    You can upload images to accompany your article. Click them to get
                    their link to use them in markdown of your article.
                </div>
                <ul id="gallery-preview">
                    <!-- This content is generated by a JS script!  -->
                </ul>
            </div>
        </div>
        <h2>Downloads & Links</h2>
        <div class="field">
            The project needs to provide at least 1 file or link for the audience to download. <br>
            Max file upload size is 35MB. Max URL length is 200. <br>
            Display name can be up to 96 characters long. <br>
        </div>
        <div class="downloads-part">
            <div class="field">
            <h3>Add a link</h3>
            <div id="link-adder" class="adder">
                <div class="field">
                    <p>Link #1 to download the project.</p>
                    <label for="input-link-url-0">URL:</label>
                    <input type="text" name="link-url[0]" id="input-link-url-0">
                    <label for="input-link-name-0">Display Name:</label>
                    <input type="text" name="link-name[0]" id="input-link-name-0">
                </div>
            </div>
            </div>
            <div class="field">
            <h3>Upload a file</h3>
            <div id="file-adder" class="adder">
                <div class="field">
                    <p>File #1 to download the project.</p>
                    <label for="input-file-url-0">File Upload:</label>
                    <input type="file" name="file-upload[0]" id="input-file-url-0">
                    <label for="input-file-name-0">Display Name:</label>
                    <input type="text" name="file-name[0]" id="input-file-name-0">
                </div>
            </div>
            </div>
            <input type="submit" value="Create Project">
        </div>
        <input type="hidden" name="editing" value="<?= $prefillEditing ?>">
        <input type="hidden" name="csrf-token" value="<?= $csrfToken ?>">
    </form>
</main>